version: 2
snapshot:
  widths: [360, 768, 1024, 1440]
  min-height: 1024
  percy-css: |
    /* Hide dynamic content that might cause false positives */
    [data-testid="timestamp"],
    .loading-spinner,
    .skeleton {
      visibility: hidden !important;
    }

discovery:
  request-headers:
    User-Agent: Percy

browser:
  executable: /usr/bin/google-chrome-stable
